name: cleanup

on:
  pull_request:
    types: [ closed ]

jobs:
  cache:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
      BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
    runs-on: ubuntu-latest
    steps:
      - 
        name: Cleanup cache(s) for the pull request
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete $cacheKey
          done
          echo "Done"
